import { createHmac, timingSafeEqual } from 'node:crypto';
import { copyFile, mkdir, open, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { dirname, join, normalize, resolve, sep } from 'node:path';
import type {
  ObjectHead,
  PresignOptions,
  PresignedDownload,
  PresignedUpload,
  Storage,
} from './types';

/**
 * Disk-backed storage for development and tests.
 *
 * Deliberately not a stub. It signs URLs, honours expiry, enforces the size
 * cap and rejects tampered keys — because a development implementation that
 * accepts anything means the first time the signing path is exercised is in
 * production against a real bucket.
 *
 * The signature is an HMAC of the key, expiry and method, which is the same
 * shape of thing SigV4 does, minus the parts that only matter to AWS.
 */
export interface LocalStorageOptions {
  /** Where objects are written. */
  root: string;
  /** Signing secret. Development-only; never shared with a real bucket. */
  secret: string;
  /** Origin the signed URLs point at, e.g. http://localhost:3000. */
  publicOrigin: string;
  /** Route that serves them. */
  routePath?: string;
}

export type SignedMethod = 'PUT' | 'GET';

export class LocalStorage implements Storage {
  private readonly root: string;
  private readonly secret: string;
  private readonly origin: string;
  private readonly routePath: string;

  constructor(options: LocalStorageOptions) {
    this.root = resolve(options.root);
    this.secret = options.secret;
    this.origin = options.publicOrigin.replace(/\/$/, '');
    this.routePath = options.routePath ?? '/api/dev-storage';
  }

  /**
   * Resolves a key to a path, refusing anything that climbs out of the root.
   *
   * Keys are generated by us, so this should never trigger — which is exactly
   * why it is here. A path traversal that only becomes reachable after a
   * refactor is the kind that ships.
   */
  private pathFor(key: string): string {
    const full = resolve(join(this.root, normalize(key)));
    if (full !== this.root && !full.startsWith(this.root + sep)) {
      throw new Error(`storage: key escapes the root: ${key}`);
    }
    return full;
  }

  sign(key: string, method: SignedMethod, expiresAtMs: number, maxBytes?: number): string {
    const payload = [method, key, String(expiresAtMs), String(maxBytes ?? '')].join('\n');
    return createHmac('sha256', this.secret).update(payload).digest('hex');
  }

  /** Constant-time, and false rather than throwing on a malformed signature. */
  verify(
    key: string,
    method: SignedMethod,
    expiresAtMs: number,
    signature: string,
    maxBytes?: number,
  ): boolean {
    if (!Number.isFinite(expiresAtMs) || Date.now() > expiresAtMs) return false;
    const expected = this.sign(key, method, expiresAtMs, maxBytes);
    const a = Buffer.from(expected, 'utf8');
    const b = Buffer.from(signature, 'utf8');
    if (a.length !== b.length) return false;
    return timingSafeEqual(a, b);
  }

  private url(key: string, method: SignedMethod, options?: PresignOptions): {
    url: string;
    expiresAt: Date;
  } {
    const seconds = options?.expiresInSeconds ?? (method === 'PUT' ? 900 : 3600);
    const expiresAt = new Date(Date.now() + seconds * 1000);
    const signature = this.sign(key, method, expiresAt.getTime(), options?.maxBytes);

    const search = new URLSearchParams({
      key,
      method,
      exp: String(expiresAt.getTime()),
      sig: signature,
    });
    if (options?.maxBytes !== undefined) search.set('max', String(options.maxBytes));

    return { url: `${this.origin}${this.routePath}?${search.toString()}`, expiresAt };
  }

  async presignPut(key: string, options?: PresignOptions): Promise<PresignedUpload> {
    const { url, expiresAt } = this.url(key, 'PUT', options);
    return {
      url,
      headers: options?.contentType ? { 'content-type': options.contentType } : {},
      expiresAt,
    };
  }

  async presignGet(key: string, options?: PresignOptions): Promise<PresignedDownload> {
    return this.url(key, 'GET', options);
  }

  async head(key: string): Promise<ObjectHead | null> {
    try {
      const info = await stat(this.pathFor(key));
      const meta = await this.readMeta(key);
      return { bytes: info.size, contentType: meta?.contentType ?? null };
    } catch {
      return null;
    }
  }

  async readHead(key: string, bytes: number): Promise<Uint8Array> {
    const handle = await open(this.pathFor(key), 'r');
    try {
      const buffer = Buffer.alloc(bytes);
      const { bytesRead } = await handle.read(buffer, 0, bytes, 0);
      return new Uint8Array(buffer.subarray(0, bytesRead));
    } finally {
      await handle.close();
    }
  }

  async downloadTo(key: string, path: string): Promise<void> {
    await mkdir(dirname(path), { recursive: true });
    await copyFile(this.pathFor(key), path);
  }

  async uploadFrom(key: string, path: string, contentType: string): Promise<void> {
    const target = this.pathFor(key);
    await mkdir(dirname(target), { recursive: true });
    await copyFile(path, target);
    await this.writeMeta(key, contentType);
  }

  async delete(key: string): Promise<void> {
    await rm(this.pathFor(key), { force: true });
    await rm(`${this.pathFor(key)}.meta`, { force: true });
  }

  /** Used by the dev route once a signature checks out. */
  async put(key: string, body: Uint8Array, contentType?: string): Promise<void> {
    const target = this.pathFor(key);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, body);
    if (contentType) await this.writeMeta(key, contentType);
  }

  async get(key: string): Promise<{ body: Uint8Array; contentType: string | null } | null> {
    try {
      const body = new Uint8Array(await readFile(this.pathFor(key)));
      const meta = await this.readMeta(key);
      return { body, contentType: meta?.contentType ?? null };
    } catch {
      return null;
    }
  }

  private async writeMeta(key: string, contentType: string): Promise<void> {
    await writeFile(`${this.pathFor(key)}.meta`, JSON.stringify({ contentType }));
  }

  private async readMeta(key: string): Promise<{ contentType: string } | null> {
    try {
      return JSON.parse(await readFile(`${this.pathFor(key)}.meta`, 'utf8')) as {
        contentType: string;
      };
    } catch {
      return null;
    }
  }
}
