/**
 * GENERATED by scripts/bundle-migrations.mjs. Do not edit.
 *
 * Run `pnpm --filter @editz/db generate` after changing the schema.
 */

export interface BundledMigration {
  tag: string;
  /** Statements, already split on drizzle's breakpoint marker. */
  statements: string[];
}

export const MIGRATIONS: readonly BundledMigration[] = [
  {
    "tag": "0000_dizzy_iceman",
    "statements": [
      "CREATE TYPE \"public\".\"execution_mode\" AS ENUM('client', 'server');",
      "CREATE TYPE \"public\".\"job_status\" AS ENUM('queued', 'processing', 'done', 'failed');",
      "CREATE TYPE \"public\".\"plan\" AS ENUM('free', 'pro');",
      "CREATE TYPE \"public\".\"subscription_status\" AS ENUM('active', 'past_due', 'cancelled', 'expired');",
      "CREATE TABLE \"jobs\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"user_id\" uuid,\n\t\"anon_fingerprint\" text,\n\t\"tool_slug\" text NOT NULL,\n\t\"execution_mode\" \"execution_mode\" NOT NULL,\n\t\"status\" \"job_status\" DEFAULT 'queued' NOT NULL,\n\t\"input_bytes\" bigint NOT NULL,\n\t\"output_bytes\" bigint,\n\t\"input_key\" text,\n\t\"output_key\" text,\n\t\"params\" jsonb NOT NULL,\n\t\"error\" text,\n\t\"progress\" real DEFAULT 0 NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"started_at\" timestamp with time zone,\n\t\"finished_at\" timestamp with time zone,\n\t\"expires_at\" timestamp with time zone,\n\tCONSTRAINT \"jobs_client_has_no_input_key\" CHECK ((\"jobs\".\"execution_mode\" = 'server' AND \"jobs\".\"input_key\" IS NOT NULL)\n          OR (\"jobs\".\"execution_mode\" = 'client' AND \"jobs\".\"input_key\" IS NULL)),\n\tCONSTRAINT \"jobs_progress_range\" CHECK (\"jobs\".\"progress\" >= 0 AND \"jobs\".\"progress\" <= 1),\n\tCONSTRAINT \"jobs_has_an_owner\" CHECK (\"jobs\".\"user_id\" IS NOT NULL OR \"jobs\".\"anon_fingerprint\" IS NOT NULL)\n);",
      "CREATE TABLE \"projects\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"user_id\" uuid NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"timeline\" jsonb NOT NULL,\n\t\"thumbnail_key\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"subscriptions\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"user_id\" uuid NOT NULL,\n\t\"provider\" text NOT NULL,\n\t\"provider_ref\" text NOT NULL,\n\t\"status\" \"subscription_status\" NOT NULL,\n\t\"current_period_end\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"usage\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"user_id\" uuid,\n\t\"anon_fingerprint\" text,\n\t\"tool_slug\" text NOT NULL,\n\t\"execution_mode\" \"execution_mode\" NOT NULL,\n\t\"bytes_processed\" bigint NOT NULL,\n\t\"executed_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"usage_has_an_owner\" CHECK (\"usage\".\"user_id\" IS NOT NULL OR \"usage\".\"anon_fingerprint\" IS NOT NULL)\n);",
      "CREATE TABLE \"users\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"email\" text NOT NULL,\n\t\"name\" text,\n\t\"image\" text,\n\t\"plan\" \"plan\" DEFAULT 'free' NOT NULL,\n\t\"plan_expires_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "ALTER TABLE \"jobs\" ADD CONSTRAINT \"jobs_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "ALTER TABLE \"projects\" ADD CONSTRAINT \"projects_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"subscriptions\" ADD CONSTRAINT \"subscriptions_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"usage\" ADD CONSTRAINT \"usage_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "CREATE INDEX \"jobs_status_idx\" ON \"jobs\" USING btree (\"status\");",
      "CREATE INDEX \"jobs_expires_at_idx\" ON \"jobs\" USING btree (\"expires_at\");",
      "CREATE INDEX \"jobs_user_idx\" ON \"jobs\" USING btree (\"user_id\");",
      "CREATE INDEX \"projects_user_idx\" ON \"projects\" USING btree (\"user_id\");",
      "CREATE UNIQUE INDEX \"subscriptions_provider_ref_idx\" ON \"subscriptions\" USING btree (\"provider\",\"provider_ref\");",
      "CREATE INDEX \"subscriptions_user_idx\" ON \"subscriptions\" USING btree (\"user_id\");",
      "CREATE INDEX \"usage_user_day_idx\" ON \"usage\" USING btree (\"user_id\",\"executed_at\");",
      "CREATE INDEX \"usage_anon_day_idx\" ON \"usage\" USING btree (\"anon_fingerprint\",\"executed_at\");",
      "CREATE UNIQUE INDEX \"users_email_idx\" ON \"users\" USING btree (\"email\");"
    ]
  },
  {
    "tag": "0001_unusual_silver_fox",
    "statements": [
      "ALTER TABLE \"jobs\" DROP CONSTRAINT \"jobs_client_has_no_input_key\";",
      "ALTER TABLE \"jobs\" ADD COLUMN \"files_deleted_at\" timestamp with time zone;",
      "ALTER TABLE \"jobs\" ADD CONSTRAINT \"jobs_client_has_no_input_key\" CHECK ((\"jobs\".\"execution_mode\" = 'server'\n             AND (\"jobs\".\"input_key\" IS NOT NULL OR \"jobs\".\"files_deleted_at\" IS NOT NULL))\n          OR (\"jobs\".\"execution_mode\" = 'client' AND \"jobs\".\"input_key\" IS NULL));"
    ]
  }
];
